config/routes.rb
QuestionApp::Application.routes.draw do
  root :to => 'static_pages#welcome'
  devise_for :users
  resources :questions do
    member do
        put "like", to: "questions#like"
        put "dislike", to: "questions#dislike"
    end
    resources :answers do
        member do
            put "like", to: "answers#like"
            put "dislike", to: "answers#dislike"
        end
        resources :comments do
           member do
            put "like", to: "comments#like"
            put "dislike", to: "comments#dislike"
        end
    end
end
end

match '/welcome', :to => "static_pages#welcome"
match '/profile', :to => "profiles#show"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :question
	attr_accessible :anonymous, :answer, :commenter, :votes, :comments_attributes
	accepts_nested_attributes_for :comments
	validates :answer, presence: true, length: {minimum: 10}
	acts_as_votable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :answer
  attr_accessible :anonymous, :comment, :writer, :votes
  validates :comment, presence: true
  validates :writer, presence: true
   acts_as_votable
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  attr_accessible :query, :text, :answers_attributes
  validates :query, presence: true, length: {minimum: 15}
  accepts_nested_attributes_for :answers
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_filter :get_question
	before_filter :check_auth, :only => [:show, :index, :edit, :update, :destroy]
	def check_auth
		if !user_signed_in?
			redirect_to new_user_session_path
		end
	end
	def get_question
		@question = Question.find(params[:question_id])
	end

	def index
		@answers = @question.answers
	end

	def show
		@answer = Answer.find(params[:id])
		@comment = @answer.comments.new(params[:comment])
	end

	def create
		@answer = @question.answers.new(params[:answer])
		if @answer.anonymous == true
			@answer.commenter = "Anonymous"
		else
			@answer.commenter = current_user.username
		end
		@answer.save
		if @answer.save
			redirect_to question_path(@question)
		else
			redirect_to questions_path
		end
	end

	def like
		@answer = Answer.find(params[:id])
		@answer.liked_by current_user
		redirect_to question_path(@question)

	end

	def dislike
		@answer = Answer.find(params[:id])
		@answer.downvote_from current_user
		redirect_to question_path(@question)

	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	def after_sign_in_path_for(user)
		questions_path
	end

	def after_sign_out_path_for(resource_or_scope)
		welcome_path
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :get_question
	before_filter :check_auth, :only => [:show, :index, :edit, :update, :destroy]
	def check_auth
		if !user_signed_in?
			redirect_to welcome_path
		end
	end
	def get_question
		@question = Question.find(params[:question_id])
	end
	def create
		@answer = Answer.find(params[:answer_id])
		@comment = @answer.comments.new(params[:comment])
		@comment.writer = current_user.username
		@comment.save
		redirect_to question_answer_path(@question, @answer)
	end

	def like
		@answer = Answer.find(params[:answer_id])
		@comment = Comment.find(params[:id])
		@comment.liked_by current_user
		redirect_to question_answer_path(@question, @answer)

	end

	def dislike
		@answer = Answer.find(params[:answer_id])
		@comment = Comment.find(params[:id])
		@comment.downvote_from current_user
		redirect_to question_answer_path(@question, @answer)
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = current_user
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_filter :check_auth, :only => [:show, :index, :edit, :update, :destroy]
	def check_auth
		if !user_signed_in?
			redirect_to welcome_path
		end
	end
	def new
		@question = Question.new
	end

	def create
		@question = Question.new(params[:question])
		if @question.save
			redirect_to @question
		else
			render 'new'
		end
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		if @question.update_attributes(params[:question])
			redirect_to @question
		else
			render 'edit'
		end
	end

	def index
		@questions = Question.order("cached_votes_up").paginate(:page => params[:page])
	end

	def show
		@question = Question.find(params[:id])
		@answer = Answer.new(params[:answer]).tap { |a| a.question = @question }
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy
		redirect_to questions_path
	end

	def like
		@question = Question.find(params[:id])
		@question.liked_by current_user
		redirect_to questions_path
	end

	def dislike
		@question = Question.find(params[:id])
		@question.downvote_from current_user
		redirect_to questions_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  	render :layout => 'landing'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/answers/_answer.html.erb

<div class="container">
	<div class="row-fluid">
	</p>

	<p>
		<%= answer.answer %>
	</p>

	<p>
		<em><%= answer.commenter %></em> posted  WHY NOTHING HAPPEN<%= question.likes.size %> | 
		<%=link_to "vote up", like_answer_path(question), method: :put%> | <%=link_to "vote down", dislike_answer_path(question), method: :put%>
		<%= link_to "Answer comments", answer.id %>

	</p>
	<p>		
		<%= link_to "Answer comments", answer.id %>
	</p>

</div>
</div>
<p>
	

app/views/answers/_form.html.erb
<div class="container">
	<% if user_signed_in? %>
	<%= form_for([@question, @answer]) do |f| %>

	<p>
		<%= f.label :answer %>
		<%= f.text_area :answer, :cols => "50", :rows => "30"%>
	</p>
	<p>
				<%= label_tag(:anonymous, "Anonymous")%>
		<%= f.check_box :anonymous%>
	</p>
	<p>
		<%= f.submit "Submit Answer" %>
	</p>
	<% end %>
	<% else %>
	<p> <em>You must be signed in to answer</em> </p>
	<% end %>
</div>

app/views/answers/show.html.erb
<div class = "offset1">
<div class = "bottom-border-solid; box-shadow: 5px 3px 5px rgba(0, 0, 0, 0.5)">
<h2 style = "color: #FF8C00"><%= @answer.answer %></h2>
</div>


<%= render "comments/form"%>

<%= render @answer.comments %>

</div>

app/views/comments/_comment.html.erb
<div class="container">
	<div style = "border-bottom: 1px solid #888888">
<p> 
<%= comment.comment %>
</p>
<p> <%= comment.writer %> posted </p>

<p><%= comment.likes.size %> | 
				<%=link_to "Upvote", like_question_answer_comment_path([@question],[@answer], [comment]), method: :put%> | 
				<%=link_to "Downvote", dislike_question_answer_comment_path([@question],[@answer], [comment]), method: :put%>

			</p>
</div>
	</div>

app/views/comments/_form.html.erb
<div class="container">
	<% if user_signed_in? %>
	<%= form_for([@question, @answer, @comment]) do |f| %>

	<p>
		<%= f.label :comment %>
		<%= f.text_area :comment, :cols => "50", :rows => "30"%>
	</p>
	<p>
		<%= label_tag(:anonymous, "Anonymous")%>
		<%= f.check_box :anonymous%>
	</p>
	<p>
		<%= f.submit "Submit Comment" %>
	</p>
	<% end %>
	<% else %>
	<p> <em>You must be signed in to comment</em> </p>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<div class = "container">

	<head >
		<style>
		body {

			background: url("") no-repeat center center fixed; 
			-webkit-background-size: cover;
			-moz-background-size: cover;
			-o-background-size: cover;
			background-size: cover;
		}
		</style>

		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<title>Blog</title>
		<link href='http://fonts.googleapis.com/css?family=Exo+2' rel='stylesheet' type='text/css'>
	</head>


	<nav class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<ul class="nav">
					<li><%= link_to "TigerAnswers", questions_path%></li>
					<% if user_signed_in? %>
					<li><%= link_to "Ask", new_question_path%></li>
					<li><%= link_to "Profile", profile_path %></li>
					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
					<li><form class="navbar-search pull-right">  
						<input type="text" class="search-query" placeholder="Search">  
					</form></li>
					<% else%>
					<li><%= link_to "Sign up", new_user_registration_path %></li>
					<li><%= link_to "Sign In", new_user_session_path %></li>


					<%end%>

				</ul>
			</div>
		</div>
	</nav>
	<div class='wrapper'>
		<body style="padding-top:40px">
			<%= yield %>

		</body>
	</div>
</div>
</html>
</div>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Welcome to TigerAnswers</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Exo+2' rel='stylesheet' type='text/css'>
	<style>
	html {

		background: url(http://www.desktop-backgrounds.org/thumbs/2012/11/09/rocks-on-the-beach-hd-wallpaper.jpg) no-repeat center center fixed; 
		-webkit-background-size: cover;
		-moz-background-size: cover;
		-o-background-size: cover;
		background-size: cover;
	}
	html *{
		font-family: 'Exo 2';
	}
	body{
		background: transparent;
	}
	h1 {

		color: white;
	}
	p {
		color: white;
	}
	</style>

</head>
	<div align="right">
		<p><%= link_to "Sign In", new_user_session_path %></p>
	</div>
<body>
	<div align="center">
	<%= yield %>
</div>
</body>

</html>


app/views/profiles/show.html.erb
<h1> Welcome <%= @user.email %> </h1>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
<% if @question.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@question.errors.count, "error") %> prohibited
    this post from being saved:</h2>
    <ul>
      <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :Question %><br>
    <%= f.text_field :query %>
  </p>
  
  <p>
    <%= f.label :"Add some description"%><br>
    <%= f.text_area  :text, "width" => 80, "rows" => 20 %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/questions/edit.html.erb
<h1> Editing Question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<%= will_paginate %>
<div style="offset1">
	<h1 style = "color: #FF8C00"><em>Welcome to TigerAnswers. Share and Learn.</em></h1>

</div>
<div style = "padding-top: 5px">
</div>

<% @questions.each do |question| %>

<div class="container; offset1; ">
	<div style="border-bottom: 2px gray solid">

		<h1 style = "color: #FF8C00"><%= question.query %></h1>
		<h4>
			<%= truncate question.text, length: 400 %>
		</h4>
		<p><%= link_to 'read more', question%></p>
		<p><%= question.likes.size %> | <%=link_to "Upvote", like_question_path(question), method: :put%> | <%=link_to "Downvote", dislike_question_path(question), method: :put%></p>
	</div>
</div>
<% end %>


<%= will_paginate %>

app/views/questions/new.html.erb
<h1> New Question </h1>
<%= render 'form' %>

<%= link_to "Questions", new_question_path %>

app/views/questions/show.html.erb
<div class="container; relative; offset1">
	<div class="row-fluid">
		<h1 style = "color: #FF8C00"><%= @question.query %></h1>

		
		<h4>
			<%= @question.text %>
		</h4>
		<h5>Add an answer:</h5>


		<%= render "answers/form" %>
		<h3 style = "color: #FF8C00">Answers</h3>	

		<% if @question.answers.empty? %>
		<p> No answers yet. Why don't you add one? </p>
		<% else %>

		<% @question.answers.each do |ans| %>

		<div class="container">
			<div style ="border-bottom: 1px solid #888888; box-shadow: 5px 3px 5px rgba(0, 0, 0, 0.5)">
			</p>

			<h5>
				<%= ans.answer %>
			</h5>



			<p>
				<em><%= ans.commenter %></em> posted 
			</p>
			<p><%= ans.likes.size %> | 
				<%=link_to "vote up", like_question_answer_path([@question],[ans]), method: :put%> | <%=link_to "vote down", dislike_question_answer_path([@question],[ans]), method: :put%> | <%= link_to "Comments", [@question, ans] %>

			</p>

		</div>
	</div>
	<% end %>
	<% end %>
	<p>



		
		<!--must check the comment item-->

	</div>
</div>

app/views/static_pages/welcome.html.erb
<h1 class="margin-base-vertical"> Ever had a nagging question about campus?</h1>
<p>It's difficult to find the answers to all your questions.</p>
<p> Which classes do I take? Should I join this research lab? Any crazy hookup stories...?</p>
<p>But you want to know now. So join TigerAnswers. Ask. Answer. Learn.</p>
<button class="btn btn-success bt-lg"><%= link_to "Sign Up", new_user_registration_path %></button>